AddCSLuaFile( "autorun/AddWheelsToListExtra.lua" ) 
list.Set( "scar_wheels", "#Ilcar", { Material = "vgui/wheels_ilcar", wheelchanger_model = "models/ilcar/ilcarw.mdl" , Value = "Ilcar" } )
list.Set( "scar_wheels", "#Abrams", { Material = "vgui/wheel_abrams", wheelchanger_model = "models/tiggomods/tanks/m1a1/wheel.mdl" , Value = "Abrams" } )
list.Set( "scar_wheels", "#FordMustangRT", { Material = "vgui/wheel_mustangTR", wheelchanger_model = "models/tiggomods/vehicles/fordmustangwheel.mdl" , Value = "FordMustangRT" } )
list.Set( "scar_wheels", "#Yamahayfz450", { Material = "vgui/wheel_yamaha", wheelchanger_model = "models/tiggogm/vehicles/yamahayfz450wheel.mdl" , Value = "Yamahayfz450" } )
list.Set( "scar_wheels", "#FerrariF50", { Material = "vgui/wheel_ferrarif50", wheelchanger_model = "models/tiggomods/vehicles/ferrarif50wheel.mdl" , Value = "FerrariF50" } )
list.Set( "scar_wheels", "#LamboDiablo", { Material = "vgui/wheel_lambodiablo", wheelchanger_model = "models/tiggomods/vehicles/lambodiablowheel.mdl" , Value = "LamboDiablo" } )
list.Set( "scar_wheels", "#ViperSRT10", { Material = "vgui/wheel_vipersrt10", wheelchanger_model = "models/tiggomods/vehicles/vipersrt10wheel.mdl" , Value = "ViperSRT10" } )
list.Set( "scar_wheels", "#CarreraGT", { Material = "vgui/wheel_carreragt", wheelchanger_model = "models/tiggomods/vehicles/carreragtwheel.mdl" , Value = "CarreraGT" } )
list.Set( "scar_wheels", "#Ferrari360", { Material = "vgui/wheel_ferrari360", wheelchanger_model = "models/tiggomods/vehicles/ferrari360wheel.mdl" , Value = "Ferrari360" } )
list.Set( "scar_wheels", "#FerrariF430", { Material = "vgui/wheel_ferrarif430", wheelchanger_model = "models/tiggomods/vehicles/ferrarif430wheel.mdl" , Value = "FerrariF430" } )
list.Set( "scar_wheels", "#LamboMurci", { Material = "vgui/wheel_lambomurci", wheelchanger_model = "models/tiggomods/vehicles/lambomurciwheel.mdl" , Value = "LamboMurci" } )
list.Set( "scar_wheels", "#NissanSkyline", { Material = "vgui/wheel_nissanskyline", wheelchanger_model = "models/tiggomods/vehicles/nissanskylinewheel.mdl" , Value = "NissanSkyline" } )
list.Set( "scar_wheels", "#PaganiZonda", { Material = "vgui/wheel_paganizonda", wheelchanger_model = "models/tiggomods/vehicles/paganizondawheel.mdl" , Value = "PaganiZonda" } )
list.Set( "scar_wheels", "#Porsche911", { Material = "vgui/wheel_porsche911", wheelchanger_model = "models/tiggomods/vehicles/porsche911wheel.mdl" , Value = "Porsche911" } )
list.Set( "scar_wheels", "#JimmyGibbs", { Material = "vgui/wheel_jimmygibbs", wheelchanger_model = "models/tiggomods/vehicles/racecarwheel.mdl" , Value = "JimmyGibbs" } )
list.Set( "scar_wheels", "#ToyotaGT1", { Material = "vgui/wheel_toyotagt1", wheelchanger_model = "models/tiggomods/vehicles/toyotagt1wheel.mdl" , Value = "Toyota GT1" } )
list.Set( "scar_wheels", "#1996ChevroletCorvette", { Material = "vgui/wheel_1996corvette", wheelchanger_model = "models/tiggomods/vehicles/1996corvettewheel.mdl" , Value = "1996 Chevrolet Corvette" } )
list.Set( "scar_wheels", "#Brera", { Material = "vgui/wheel_brera", wheelchanger_model = "models/tiggomods/vehicles/brerawheel.mdl" , Value = "Brera" } )
list.Set( "scar_wheels", "#ToyotaSupraRZ", { Material = "vgui/wheel_ToyotaSupraRZ", wheelchanger_model = "models/tiggomods/vehicles/suprarzwheel.mdl" , Value = "Toyota Supra RZ" } )
list.Set( "scar_wheels", "#ViperCC", { Material = "vgui/wheels_vipercc", wheelchanger_model = "models/tiggomods/vehicles/viperccwheel.mdl" , Value = "Viper CC" } )
list.Set( "scar_wheels", "#DodgeRam", { Material = "vgui/wheel_dodgeram", wheelchanger_model = "models/tiggomods/vehicles/ramwheel.mdl" , Value = "Dodge Ram" } )